[package]
name = "needle"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
thiserror = "1.0.30"
num_cpus = "1.13.1"
tracing = "0.1.34"
tracing-subscriber = "0.2"
ffmpeg-next = { git = "https://github.com/aksiksi/rust-ffmpeg", rev = "f20fa322af00b724350eda27a88d83d0b5eada81", optional = true }
blockhash = { version = "0.4.0", optional = true }
image = { version = "0.24", optional = true }
chromaprint = { path = "../chromaprint", optional = true }
num-traits = { version = "0.2", optional = true }
clap = { version = "3", features = ["derive"] }

[features]
default = ["audio", "video"]
audio = ["chromaprint", "ffmpeg-next", "num-traits"]
video = ["blockhash", "ffmpeg-next", "image"]
