name: release-please
on:
  push:
    branches:
      - main

env:
  # Use a personal access token to be able to trigger
  # the "publish-release" workflow when when a new tag is created.
  # See: https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow
  GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: rust
