name: test

on:
  push:
    paths-ignore:
      - '*.md'
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # Cache Rust dependencies.
    - uses: Swatinem/rust-cache@v1
    - name: Install dependencies
      run: |
        sudo apt install \
          libavutil-dev \
          libavformat-dev \
          libswresample-dev \
          libavcodec-dev \
          libavfilter-dev \
          libavdevice-dev
    - name: Build debug version
      run: cargo build -v
    - name: Run tests
      run: cargo test -v
